Top Trade Brands test
Toolstation/Toolstation-Automation pull request #26
Opened 2022-01-13 14:27 UTC by mihajlo1985

- One test fails for Firefox if it is not run --headed
- The close button on the Top Trade Brands

2022-01-17 09:18 UTC, velislavaatanasova requested changes

2022-01-17 09:18 UTC, velislavaatanasova commented on Framework/tests/HomePage.spec.ts
> +    await test.step('Verify visibility of the Top Trade Brands', async () => {
why do you have this step two times?

2022-01-17 09:18 UTC, velislavaatanasova commented on Framework/tests/HomePage.spec.ts
> +    await test.step('Verify visibility of the Top Trade Brands', async () => {
please move all of this to a separate Test. Ideal would be to have this one test for checking things in the header and checking visibility of top trade brands. Then in another test specific for the top trade brands do all of these checks

2022-01-17 09:18 UTC, velislavaatanasova commented on Framework/tests/HomePage.spec.ts
> +    await test.step('Verify View All Top Trade Brands', async () => {
If you want to click on the link I would also add some check if the correct page is opened otherwise we don't get anything useful of this check.

2022-01-17 10:20 UTC, mihajlo1985 commented on Framework/tests/HomePage.spec.ts
> +    await test.step('Verify visibility of the Top Trade Brands', async () => {
Ha! By mistake I have must double pasted :D

2022-01-17 14:03 UTC, velislavaatanasova commented on Framework/common-actions/siteURLs.ts
> +    static readonly VIEW_ALL = baseURL + '/content/brands';
change it to TOP_TRADE_BRANDS_VIEW_ALL. Once we have more urls it will get confusing which one is which so it will be best to have more meaningful names

2022-01-18 11:46 UTC, velislavaatanasova approved these changes

2022-01-18 11:46 UTC, merged